### ISSUE TITLE
Key Error

### ISSUE THREAD

**Issue by VanshShah1** [NotCookey/Lexica.art#3]
Traceback (most recent call last):
  File "/Users/vanshshah/Downloads/Lexica.art-main/testimg.py", line 3, in <module>
    lex=Lexica(query="bubble", cookie=cookie).generate()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vanshshah/Downloads/Lexica.art-main/Lex.py", line 50, in generate
    imageout = [f"https://image.lexica.art/full_jpg/{ids['id']}" for ids in response.json()['images']]
                                                                            ~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'images'

**Comment by NotCookey** [comment]
The site has updated their backend api. I'll look into it.
